// <auto-generated />
using System;
using EjemploSegundoParcial.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EjemploSegundoParcial.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("EjemploSegundoParcial.Models.Llamada", b =>
                {
                    b.Property<int>("llamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("total")
                        .HasColumnType("TEXT");

                    b.HasKey("llamadaId");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("EjemploSegundoParcial.Models.LlamadaDetalle", b =>
                {
                    b.Property<int>("llamadaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("duracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("llamadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("paisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("precio")
                        .HasColumnType("TEXT");

                    b.HasKey("llamadaDetalleId");

                    b.HasIndex("llamadaId");

                    b.ToTable("LlamadaDetalle");
                });

            modelBuilder.Entity("EjemploSegundoParcial.Models.Pais", b =>
                {
                    b.Property<int>("paisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("pais")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("precio")
                        .HasColumnType("TEXT");

                    b.HasKey("paisId");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            paisId = 1,
                            pais = "Haiti",
                            precio = 10m
                        });
                });

            modelBuilder.Entity("EjemploSegundoParcial.Models.LlamadaDetalle", b =>
                {
                    b.HasOne("EjemploSegundoParcial.Models.Llamada", null)
                        .WithMany("Detalles")
                        .HasForeignKey("llamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
